web:
  build: .
  ports:
    - 80:80
  links:
    - db:mysql
  volumes:
    - .:/var/www/html:rw
db:
  image: mysql:5.6
  ports:
    - 3306:3306
  environment:
    MYSQL_DATABASE: directus
    MYSQL_ROOT_PASSWORD: docker
  volumes:
    - ./my.cnf:/etc/mysql/my.cnf:ro
